name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --dev
    - name: Lint with pylint
      run: |
        pipenv run pylint pytestgen --disable="C,W,R"
    - name: Setup coveralls config
      uses: cschleiden/replace-tokens@v1.0
      with:
        files: .coveralls.yml
      env:
        REPO_TOKEN: ${{ secrets.CoverallsRepoToken }}
    - name: Test with pytest
      run: |
        pipenv run pytest tests/ --cov pytestgen --cov-report term-missing
        pipenv run coveralls
